version: "3"

services:

  app:
    image: secure-programming/app:latest
    restart: always
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "3000:8080"
    networks:
      - backend

  database:
    image: mariadb
    restart: always
    env_file:
      - database/database.env
    ports:
      - "1306:3306"
    networks:
      - backend

networks:
  backend:
